-- 이메일 없는 비밀번호 재설정 요청 제한 기록.
-- Supabase SQL Editor에서 실행한 뒤 reset-password-no-email Edge Function을 배포하세요.

create table if not exists public.password_reset_attempts (
  id bigint generated by default as identity primary key,
  username_hash text not null,
  ip_hash text not null,
  attempted_at timestamptz not null default now()
);

create index if not exists password_reset_attempts_lookup_idx
  on public.password_reset_attempts (username_hash, ip_hash, attempted_at desc);

alter table public.password_reset_attempts enable row level security;
-- 브라우저용 정책은 만들지 않습니다. Edge Function의 service role만 접근합니다.

