-- SOLAPI SMS 인증을 사용하는 비밀번호 재설정 스키마.
-- Supabase Dashboard > SQL Editor에서 전체 내용을 한 번 실행하세요.

create extension if not exists pgcrypto;

create table if not exists public.password_reset_attempts (
  id bigint generated by default as identity primary key,
  username_hash text not null,
  ip_hash text not null,
  attempted_at timestamptz not null default now()
);

create index if not exists password_reset_attempts_lookup_idx
  on public.password_reset_attempts (username_hash, ip_hash, attempted_at desc);

alter table public.password_reset_attempts enable row level security;

create table if not exists public.password_reset_challenges (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  phone_hash text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  verify_attempts integer not null default 0,
  verified_at timestamptz,
  reset_token_hash text,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists password_reset_challenges_lookup_idx
  on public.password_reset_challenges (id, expires_at desc);

create index if not exists password_reset_challenges_phone_idx
  on public.password_reset_challenges (phone_hash, created_at desc);

alter table public.password_reset_challenges enable row level security;

-- 두 테이블 모두 브라우저용 RLS 정책을 만들지 않습니다.
-- 비밀키를 가진 Edge Function만 접근합니다.
